### ISSUE TITLE
Merge with TypeORM project?

### ISSUE THREAD

**Issue by trivikr** [typedorm/typedorm#103]
### Is your feature request related to a problem? Please describe.
The maintainers of TypeORM are accepting PRs for adding DynamoDB support as of October 2020 https://github.com/typeorm/typeorm/issues/2480#issuecomment-713267562

### Describe the solution you'd like
* Add DynamoDB support in TypeORM instead.
* Recommend TypeORM from TypeDORM README/docs.
* Archive the TypeDORM project.

### Describe alternatives you've considered
* Stick with using TypeDORM.
* Use AWS SDK for JavaScript (v3) in TypeDORM as requested in https://github.com/typedorm/typedorm/issues/102

### Additional context
The maintainer of TypeDORM @whimzyLive is aware of this update, and has already commented in Feb 2021 https://github.com/typeorm/typeorm/issues/2480#issuecomment-787652081
This issue was created just for tracking purposes.

**Comment by whimzyLive** [comment]
Hi @trivikr , 

This is indeed a good direction to go ahead in, but this library was written mainly to work with DynamoDB's ["single table design pattern"](https://www.alexdebrie.com/posts/dynamodb-single-table/), and I do agree to some extent, it does offer support for working with multiple tables.
  
I am very much keen to see DynamoDB's support in TypeDORM, for which I will do a separate PR and port some logic over from TypeDORM to TypeORM, and once that happens TypeDORM can focus entirely on improving UX for single table design patterns, and TypeORM can be the defacto object mapper for DynamoDB.
