### ISSUE TITLE
bug: findOne returns an object when it should not

### ISSUE THREAD

**Issue by flisboac** [typedorm/typedorm#110]
Howdy!

I've been using TypeDORM in one of my projects recently, and it has been good so far! Except for one problem: even when there is no item with a primary key in a table, EntityManager will always return an object (although empty). This breaks some other things, like `EntityManager.exists` and other places in the library that may depend on those functions somehow.

https://github.com/typedorm/typedorm/blob/6ccc93e376905a82412f09d7bb62f29bb5ea57fb/packages/core/src/classes/manager/entity-manager.ts#L153-L158

In `EntityManager.ts:155`, even though `response.Item` may be undefined, the implementation disregards that non-existence and just forces object conversion (to the desired entity class) with an empty object. The result is that the function does not really comply with its interface, and the `Promise<Entity | undefined>` return type is really just `Promise<Entity | {}>`, which is... not ideal, to say the least (as it will potentially and inadvertently break invariants of the entity class, which the library have no knowledge of, for obvious reasons).

In my application, I use `EntityManager.exists` with a primary key (PK + SK) to check for the existence of an entity, and to determine whether to call create or update. But because `EntityManager.findOne` always returns an object even when the primary key does not exist, `EntityManager.exists` in turn will always return true:
 https://github.com/typedorm/typedorm/blob/6ccc93e376905a82412f09d7bb62f29bb5ea57fb/packages/core/src/classes/manager/entity-manager.ts#L215-L217

Perhaps `EntityManager.findOne`'s implementation should really end up like so:

```ts
    // ...
    if (response.Item) {
      const entity = this._entityTransformer.fromDynamoEntity<Entity>(
        entityClass,
        response.Item
      );
      return entity;
    }
    return undefined;
  }
```

But I may be wrong, hence why I opened this issue. Is my analysis correct?

**Comment by whimzyLive** [comment]
@flisboac Good to hear that you are enjoying working with TypeDORM.
For the analysis, You are definitely on the right track, and yes `findOne` should be returning undefined/null in cases where the requested item entity not found.

**Comment by flisboac** [comment]
@whimzyLive that was the fastest bug delivery ever, thank you very much! 🙇‍♂️
