### ISSUE TITLE
Entity subclass without Attributes causes error

### ISSUE THREAD

**Issue by seantalbot-jisc** [typedorm/typedorm#138]
Hi, thanks for the nice library. I'm having some trouble with Entity inheritance as per https://github.com/typedorm/typedorm/blob/main/docs/entity-inheritance.md.

My use case is to have an abstract base class that defines most of the attributes I need, then create subclasses that inherit those attributes, and in some cases add their own, but often only use the inherited ones, and simply change the Entity PK/SK mappings to differentiate them in DDB. But this doesn't work, for example:

```ts
abstract class BaseEntity {
    @Attribute()
    foo: string;
}

@Entity({
    name: "SubEntity"
    primaryKey: {
        partitionKey: "whatever"
    },
})
class SubEntity extends BaseEntity {
   // no attributes
}
```
Causes this error:
```
Error: No entity with name "SubEntity" could be resolved,
      make sure they have been declared at the connection creation time.
```

Adding a single `@Attribute()` to `SubEntity` _does_ work, but I don't want to do that. The alternative is to declare some of the shared attributes in each subclass, which isn't very DRY. 

Can this be fixed, or is there another way to do this?

**Comment by whimzyLive** [comment]
@seantalbot-jisc  Glad that you liked it. I will get that fixed soon.

Thank you for reporting the issue.
