### ISSUE TITLE
Optimize update by statically verifying update value

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#150]
When updating an item using `entityManager.update` it is possible to have attributes in the body with the same value as current, which would make TypeDORM interpret it as an update with primary key attributes, which in reality is the same.

Basically, if the update body contains a primary key attribute, compare it with current value provided in primary key, if they are the same, exclude it from the update.

**Comment by mishabruml** [comment]
mind if i take this?

**Comment by whimzyLive** [comment]
Sure, here you go.
