### ISSUE TITLE
Fix typo in docs

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#165]
In some parts of the documentation,  `AutoGenerateAttribute` is referred to as  `AutoGeneratedAttribute`. This needs to be updated to correctly name the decorator.

<div type='discussions-op-text'>

<sup>Originally posted by **meeech** August 26, 2021</sup>
👋🏼 @whimzyLive I notice in the docs you make reference to `AutoGeneratedAttribute`, but it seems the decorator is `AutoGenerateAttribute`. 
I'm assuming you would want the docs updated to show using `AutoGenerateAttribute` as opposed to changing the name of the decorator to `AutoGeneratedAttribute`. 
Just wanted to check in with you before I do that - i'm building up a PR of small doc fixes as I work through getting typedorm setup in my project.

let me know</div>

**Comment by meeech** [comment]
👋🏼 assign to me 😀

**Comment by whimzyLive** [comment]
@meeech all yours. :)
