### ISSUE TITLE
Return auto-generated properties from managers

### ISSUE THREAD

**Issue by jasonvasquez** [typedorm/typedorm#176]
Hello!

I have a case where I am creating multiple records via `BatchManager`.  Part of the PartitionKey is generated using the `UUID4` strategy. For example:

```typescript
  @AutoGenerateAttribute({
    strategy: AUTO_GENERATE_ATTRIBUTE_STRATEGY.UUID4,
  })
  public id!: string;
```

As I'm writing a repository function, I don't see a way to return the item that I've just created (or items), or more importantly, I don't have a great way to find them if I tried to run another query to read them back.

I'm wondering if there's an extension point I can use to "pre-generate" the auto-generated values before sending the entities through the BatchManager , or, alternatively, a way to grab the transformed entities after the fact.

As an alternative, I can probably just pre-populate those values myself, but i was wondering if there was an expected way to accomplish this.

Thanks!

**Comment by whimzyLive** [comment]
Hi @jasonvasquez 

You are correct, currently, there is no direct way to return access auto-generated properties when using the batch manager and also there is no `pre-generate`  extension ATM.  The only way I see this working (which you are already doing) is to pre-populate the entity and not use the auto-generate decorators.

However, I can look into implementing an `option` on batch write to optionally return written items in the order they were requested to be inserted, which I imagine will not be too hard to implement.
