### ISSUE TITLE
AutoGenerateAttribute decorator doesn't autogenerate ID for entitites

### ISSUE THREAD

**Issue by franco-roura** [typedorm/typedorm#178]
Hello, I tried following [this guide](https://github.com/typedorm/typedorm/blob/main/docs/guide.md#creating-an-entity) to create an entity and try the library, my `User` entity is practically copy-pasted from the guide 

The entityManager throws `"id" was referenced in USER#{{id}} but it's value could not be resolved.` if I try to do
```typescript
const user = new User()
user.name = 'Loki';
user.status = 'active';
user.email = 'loki@asgard.com'
const response = await db.create(user)
```
![image](https://user-images.githubusercontent.com/58178352/138392009-1575417d-ae5d-40eb-9c55-1f22c8ad1b8c.png)

It doesn't throw when I manually set the ID though
![image](https://user-images.githubusercontent.com/58178352/138392644-9892ee45-b560-4be5-a83d-4b0c1fd51293.png)

Also, I'm using a local DynamoDB container (in case it matters).

**Comment by whimzyLive** [comment]
Hi @franco-roura 

Closing this as I have not seen any more updates from you. 
If the issue continues please feel free to reopen.
