### ISSUE TITLE
Could not resolve primary key on find.

### ISSUE THREAD

**Issue by Snosky** [typedorm/typedorm#189]
Hello,

I'm trying to do a simple find on a GSI but I have the error `"id" was referenced in ITEM#{{id}} but it's value could not be resolved.` even if it's not used in the request

Here is my code

```typescript
import { Attribute, AUTO_GENERATE_ATTRIBUTE_STRATEGY, AutoGenerateAttribute, Entity, INDEX_TYPE } from '@typedorm/common';

@Entity({
  name: 'item',
  primaryKey: {
    partitionKey: 'ITEM#{{id}}',
    sortKey: 'ITEM#{{id}}',
  },
  indexes: {
    GSI1: {
      type: INDEX_TYPE.GSI,
      partitionKey: 'PARENT#{{parentId}}',
      sortKey: 'CREATED_AT#{{createdAt}}',
    },
  },
})
export class Item{
  @AutoGenerateAttribute({
    strategy: AUTO_GENERATE_ATTRIBUTE_STRATEGY.UUID4,
  })
  id!: string;

  @Attribute()
  parentId!: string;

  @AutoGenerateAttribute({
    strategy: AUTO_GENERATE_ATTRIBUTE_STRATEGY.EPOCH_DATE,
  })
  createdAt: string;

  @AutoGenerateAttribute({
    strategy: AUTO_GENERATE_ATTRIBUTE_STRATEGY.EPOCH_DATE,
    autoUpdate: true,
  })
  updatedAt: string;
}

// Dynamodb request
const items = await entityManager.find(Item, { parentId: "parent-1", queryIndex: "GSI1" })
// ERROR [ExceptionsHandler] "id" was referenced in ITEM#{{id}} but it's value could not be resolved.
```

**Comment by whimzyLive** [comment]
@Snosky,

The way you are trying to read the entity is incorrect. With one of the previous releases, the option for specifying the `queryIndex` was moved to `queryOptions`. 

Please have a look at the current API for `find` [here](https://github.com/typedorm/typedorm/blob/main/docs/api.md#entitymanagerfind)

So the find in your case should look like this
```typescript
const items = await entityManager.find(Item, { parentId: "parent-1"}, { queryIndex: "GSI1" })
```
 
 Can you also let me know from where you found the above example (if found from the docs), so I can also update it?

**Comment by michael-pont** [comment]
I found it here in the docs: https://github.com/typedorm/typedorm/blob/main/docs/guide.md#step-by-step-guide
Just ctrl+f for queryIndex.

**Comment by Snosky** [comment]
@whimzyLive Thank you for your reply. The link @michael-pont give was were I found it.
