### ISSUE TITLE
BaseTransformer is broken due to class-transformer breaking changes

### ISSUE THREAD

**Issue by renanbatel** [typedorm/typedorm#190]
A new fix version of class-transform (0.4.1) added some breaking changes to the library as you can see [here](https://github.com/typestack/class-transformer/issues/1010). Your library is not using an exact version for class-transformer, it's using the caret `^` symbol, so it's pulling the broken version on a fresh installation. You could use an exact version (0.4.0) for it or update it to the last version and do the proper adjustments.

**Comment by whimzyLive** [comment]
@renanbatel ,

Thanks for letting me know. 

This is the classic issue with SemVer. I was not expecting to see such a breaking change to be released in a patch version. 
I will do a new patch release tonight that uses an exact version.

**Comment by whimzyLive** [comment]
FYI, @renanbatel
The maintainer of the `class-transformer` package has already released a new minor version (0.5.1), in which the functions are added back and marked as deprecated.

However, I will still be releasing a patch version using the new function signatures.

**Comment by whimzyLive** [comment]
Verified that the latest release 0.5.1 works correctly. So there is no need for a patch from our side.

**Comment by renanbatel** [comment]
Sorry, I don't think I get it, are you still going to fix it? It still not working for me as it pulls the 0.4.1 version when I install the library. Your package.json defines the class-transformer dependency version as `^0.4.0`, so it only updates to versions that do not increment the first non-zero portion of the version number, it does not update to 0.5.x versions, you can verify that [here](https://semver.npmjs.com/).

**Comment by whimzyLive** [comment]
@renanbatel 
 You are correct, for non-zero it only goes up to 0.4.1 with yarn.

I will reopen this issue.

**Comment by renanbatel** [comment]
@whimzyLive 

It's still not working for me, I saw that you locked class-transformer to `0.4.0` on `package.json`, but on `packages/core/package.json` and `packages/common/package.json` class-transformer dependency is still set to `^0.4.0`, I think that is making yarn pull version 0.4.1 on install.
