### ISSUE TITLE
ULID primary key

### ISSUE THREAD

**Issue by romcok** [typedorm/typedorm#221]
I would appreciate the ability to generate ULID identifier as AUTO_GENERATE_ATTRIBUTE_STRATEGY, or the ability to create my own strategy. From what I've read from the code, that's not possible yet. Is there another option than generating the id by myself when creating the record?

Thanks.

**Comment by whimzyLive** [comment]
Hi @romcok,

You can use `@Attribute` instead and have it use your strategy to generate default values.
Check the [API](https://github.com/typedorm/typedorm/blob/main/docs/api.md#attribute) for more information.

something like 

```typescript
import { ulid } from ''some-package";

@Attribute(
  default: ()=> ulid(); 
)
myId: string
```

**Comment by romcok** [comment]
Oh great, thank you for the advice 🙏
