### ISSUE TITLE
Fix incorrect document for queryIndex in "How It Works" section.

### ISSUE THREAD

**Issue by ChristopherGillis** [typedorm/typedorm#222]
The [How It Works](https://github.com/typedorm/typedorm/blob/beta/docs/how-it-works.md#given-2) page shows that the .find() method accepts `queryIndex` as a property of the second argument, but the [Step By Step Guide](https://github.com/typedorm/typedorm/blob/beta/docs/guide.md#query-1-m-relations) page shows it as a property of the third argument. I believe the example from Guide is correct. `queryIndex` should be a prop of `queryOptions` which is the third argument.

**Comment by ChristopherGillis** [comment]
In general I would love to see much more detailed documentation around how to query, paginate, etc. I'm digging through the codebase trying to figure out how it's supposed to work, because the docs are very minimal. Super appreciate what you've done here... this is just my feature request. :)

**Comment by whimzyLive** [comment]
@ChristopherGillis The later one in Step by step guide is correct. In the early development phase, `queryIndex` used to be in the second argument but later got moved to third, but that area of documentation would have been left out.

Will you be open to doing a PR, to fix the doc? 

Also, we have a task in the pipeline to work on the documentation https://github.com/typedorm/typedorm/issues/10.

**Comment by michael-pont** [comment]
@whimzyLive I added this here: https://github.com/typedorm/typedorm/pull/239
