### ISSUE TITLE
Are data types other than string not supported for table sort key?

### ISSUE THREAD

**Issue by jgcman** [typedorm/typedorm#223]
Hello, 

Are data types other than string not supported for table sort key?
If a number type other than string is used as a sort key for a table, an error occurs when inserting data.

`[Nest] 3768   - 2022. 03. 24. 오후 6:34:10   [ExceptionsHandler] One or more parameter values were invalid: Type mismatch for key createdAt expected: N actual: S +2551ms`

The data type of the sort key variable ( = createdAt ) of the table is configured as number .
Both the model and the entity have well specified number for that variable.

```
export const mytable = new Table({
	name: "mytable",
	partitionKey: "userId",
	sortKey: "createdAt",
})

@Entity({
	name: "visitEventEntity",
	primaryKey: {
		partitionKey: "{{userId}}",
		sortKey: "{{createdAt}}",
	},
})
export class VisitEventEntity {
	@Attribute()
	userId: string
	@Attribute()
	createdAt: number
}
```
I wonder if the sort key of the table must be a string, or if there is another solution.

**Comment by whimzyLive** [comment]
@jgcman There is also an ["alias"](https://github.com/typedorm/typedorm/blob/main/docs/how-to-recipes.md#define-an-entity-with-index) attribute, which might help with the scenario.

So using the alias attribute, your entity will now look something like

```typescript

@Entity({
	name: "visitEventEntity",
	primaryKey: {
		partitionKey: "{{userId}}",
		sortKey: {alias: 'createdAt'},
	},
})
export class VisitEventEntity {
	@Attribute()
	userId: string
	@Attribute()
	createdAt: number
}
```

**Comment by whimzyLive** [comment]
Closing this, as it has been open for a while, and have not heard anything back from you @jgcman.

If you think this is still an issue, please feel free to reopen this issue.
