### ISSUE TITLE
Is it possible to call a WHERE IN sql query with typedorm?

### ISSUE THREAD

**Issue by jgcman** [typedorm/typedorm#224]
Hello,

The dynamodb partiql I am using is as follows.
In the example code below, 'thingName' is the partition key of 'myTable'.

```
SELECT * FROM "myTable" WHERE "thingName" IN [ "aaaa", "bbbb", "cccc", "dddd" ]
```

Is there any way to implement this with typedorm ? Please guide. :)

**Comment by whimzyLive** [comment]
Please have a look at the example for using the query operands [here](https://github.com/typedorm/typedorm/blob/main/docs/how-to-recipes.md#apply-filter-to-query)

**Comment by jgcman** [comment]
@whimzyLive Thanks for your help :)
