### ISSUE TITLE
use fast-check for more exhaustive unit testing

### ISSUE THREAD

**Issue by mishabruml** [typedorm/typedorm#227]
I use https://github.com/dubzzz/fast-check a lot and really like it. I would be happy to make a PR to start using the library for testing some of typedorm's core functionality?

**Comment by whimzyLive** [comment]
@mishabruml 

I am not much familiar with the concept of property-based testing. 
It seems that you are having very much experience with it, are you able to provide a higher-level overview of what it is and how will it be useful in TypeDORM?  😀

**Comment by whimzyLive** [comment]
Closing this as it is no longer active.
