### ISSUE TITLE
Attribute transformation is not working when different version of class-transformer installed

### ISSUE THREAD

**Issue by imione** [typedorm/typedorm#229]
Hello👋

As I mentioned as title, attribute transformation is not working when different version of class-transformer is installed.
I think this issue could be quite serious.

My entity:
```typescript
@Entity({
  name: 'Example',
  primaryKey: {
    partitionKey: 'Example#{{id}}',
    sortKey: 'Example#{{id}}',
  },
})
export class Example {
  @Attribute()
  id: string;

  @Attribute()
  @TransformToDynamo((param: { value: string }) => 'transformed:' + param.value)
  title: string;
}
```
I expected that title must add "transformed" before the entity is saved.
Without class-transformer installation, it works very well.
But after I install `class-transformer@0.4.1`, it did not work anymore.
So I traced the problem.

```json
// package.json would be

"dependencies": {
  "@typedorm/common": "^1.14.10",
  "@typedorm/core": "^1.14.10",
  "aws-sdk": "^2.1102.0",
  "class-transformer": "^0.4.1",
  // ...
},

// package-lock.json would be sort of
"class-transformer": {
  "version": "0.4.1"
},
"@typedorm/common": {
  "dependencies": {
    "class-transformer": {
      "version": "0.4.0"
    }
},
"@typedorm/core": {
  "dependencies": {
    "class-transformer": {
      "version": "0.4.0"
    }
  }
}
```

Now, `@typedorm/core`, `@typedorm/common` depends class-transformer@v0.4.0 in each `node_modules` directory.
It means each class-transformer become isolated, so it won't share variable anymore.

Before you understand the problem more, you must know how class-tranformer implements `MetadataStorage`.
In `@Transform` decorator, you will see `defaultMetadataStorage`. ([reference](https://github.com/typestack/class-transformer/blob/ab093a355be420978273b675d3bbd3a520d1918d/src/decorators/transform.decorator.ts#L13-L20))
This is a singleton instance comes from [storage.ts](https://github.com/typestack/class-transformer/blob/v0.4.0/src/storage.ts).
The storage contains metadata used for transformation. I think this is very important.
 
Comeback to the problem, we can guess why attribute transformation did not work.
Remind that:
- `@TransformToDynamo` is defined in package `@typedorm/common`.
- Entity transformation is processed in BaseTransformer, and the class defined in `@typedorm/core`.

I will call metadataStorage instances as:
- metadataStorage in class-transformer of @typedorm/common package (A)
- metadataStorage in class-transformer of @typedorm/core package (B)

Then,
1. Transformation metadata assigned into (A). (@TransformToDyanmo)
2. ClassTransformer tries to find metadata from (B) because transformation is executed in @typedorm/core.
3. But (B) is empty, no transformation will be executed 🥲

Now I see why my codes works fine when only typedorm installed.
All packages follows class-transformer in root node_modules. Not their own.
So, common defines metadata in and core can read metadata from same metadataStorage instance.

I guess there are some options to solve this problem.
1. Stick together those two packages(common, core) into one.
2. Migrate '[decorators](https://github.com/typedorm/typedorm/tree/main/packages/common/src/decorators)' from common to core package
3. Migrate '[transformers](https://github.com/typedorm/typedorm/tree/main/packages/core/src/classes/transformer)' from core to common package.

(IMHO, I don't make sense what benefit dividing into two packages gives.
Both packages are necessary to use typedorm system, so it doesn't matter packages become one.
And not huge package yet as well.)

Anyway, I choosed option 2 (It is the easiest way that I can test in local environment).
I moved the decorators to core package.

My entity is now:
```typescript
import { Attribute, Entity } from '@typedorm/common';
import { TransformToDynamo } from '@typedorm/core';

@Entity({
  name: 'ExampleTable',
  primaryKey: {
    partitionKey: 'Example#{{id}}',
    sortKey: 'Example#{{id}}',
  },
})
export class Example {
  @Attribute()
  id: string;

  @Attribute()
  @TransformToDynamo((param: { value: string }) => 'transformed:' + param.value)
  title: string;
}
```

It works well!
<img width="422" alt="image" src="https://user-images.githubusercontent.com/4933085/160664687-c2314753-5fed-4fcb-a665-4a83956811d5.png">

You can follow sample code in my github repository
- [installed only typedorm package, working](https://github.com/imione/typedorm-sample)
- [installed different version of class-transformer, not working](https://github.com/imione/typedorm-sample/tree/example/attribute-transfomation-not-working)

I wonder what is your plan to fix :)
And I hope the problem become fixed quickly, because now I am trying to this amazing library into my product ASAP 😁
If it was only tiny bug fix, I have could create PR, but it seems like creating breaking changes, so I should ask first.

I appreciate that your effort to this project!

**Comment by imione** [comment]
@whimzyLive I am looking forward to get your reply 🙂

**Comment by whimzyLive** [comment]
@imione Sorry missed this. 
This is an interesting one. I don't think this is an issue with TypeDORM-managed metadata, rather this seems like an issue with the underlying class-transformer package.

TypeDORM does not store or manage `Transform*` metadata, they are simple wrappers around a `class-transformer` provided decorators. 

Moreover, the way metadata is managed in the TypeDORM is by referencing the metadata storage singleton - holding the applied metadata to the [Symbol](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/for) type. This guarantees the availability of the same instance within a process, so access to the singleton residing in two separate packages is a non-issue. 

I will suggest raising this with the `class-transformer` team. Otherwise, I will have a look at this in more detail and see if there is any patch that can be applied from our side, meanwhile, the proper fix is available in the `class-transformer` package.

**Comment by whimzyLive** [comment]
Closing this as it is no longer active.
