### ISSUE TITLE
Problem updating empty index with `id` in sort key [ Achieved by #150 ]

### ISSUE THREAD

**Issue by romcok** [typedorm/typedorm#235]
Hi,
I ran into a problem updating an empty index when a value in the PK of the index is not defined when creating the entity.

Here is my entity definition:

```typescript
export const ProductPrefix = 'PRD'
@Entity({
  name: 'Product',
  primaryKey: {
    partitionKey: `ID#{{id}}`,
    sortKey: ProductPrefix,
  },
  indexes: {
    GSI1: {
      partitionKey: `${EventPrefix}#{{eventId}}`,
      sortKey: `${ProductPrefix}#{{id}}`,
      type: INDEX_TYPE.GSI,
    }
  }
})
export class ProductEntity extends BaseEntity {
  @Attribute({
    default: (entity: BaseEntity) => entity.id || ulid()
  })
  id: string

  @Attribute()
  eventId: string

  @Attribute()
  title: string
  ...
}
```

When I create an item without `eventId` which is listed in GSI1 PK, my record looks like this:
```typescript
{
 "PK": "ID#01FZWVQ4JD5M2H3GSCP8JJZ48E",
 "SK": "PRD",
 "createdAt": "2022-04-05T12:38:14.128Z",
 "__en": "Product",
 "updatedAt": "2022-04-05T12:38:14.128Z",
 "id": "01FZWVQ4JD5M2H3GSCP8JJZ48E",
 "title": "Lorem ipsum dolor sit amet"
}
```
There is no GSI1 defined in the record, which is okay because I didn't provide `eventId` needed for GSI1PK. The problem is when I want to update the index and assign the Product entity to Event. This index needs two values to be updated properly. It's `id` and `eventId`. When I do update the record with these values I get InvalidPrimaryKeyAttributesUpdateError error:
```
Primary key attribute and non primary key attributes can not be
    updated together. When updating attributes that references a primary key, it can not have
    additional non key attributes.
Affected Primary key attributes: {"PK":"ID#01FZWQS0PHHSMHQYJ7M4WNTT3T"}
Tried to update non-key attributes: ["eventId"]
```
I understand that I can't update the primary key and index at the same time, but I need to use this id in the index without updating the primary key. If I do not specify the id in the update there is just GSI1PK added to the record `"GSI1PK": "EVT#01FZWFCDFHEPH3CM87YV61SN4T"` wihout sort key.

My current solution is to set `eventId` to` NONE` during creation and change this value on update. This works, but it's not ideal. Is there any other way to solve this?

Thanks 🙏

**Comment by romcok** [comment]
Adding `NONE` to the transformation temporarily solved my problem.

```typescript
export class ProductEntity extends BaseEntity {
  @Attribute({
    default: (entity: BaseEntity) => entity.id || ulid()
  })
  id: string

  @Attribute({
    default: () => NoneValue,
  })
  @TransformFromDynamo(({value}: {value: string}) => value === NoneValue ? null : value)
  @TransformToDynamo(({value}: {value: string}) => !value ? NoneValue : value)
  eventId: string

  @Attribute()
  title: string
  ...
}
```

**Comment by whimzyLive** [comment]
Hey @romcok 
This is a known limitation of TypeDORM. 
However, in your case, this should get resolved when https://github.com/typedorm/typedorm/issues/150 is implemented.

It will better analyze the update values and if the id by which we are trying to update is the same as the one being passed in as the new value, TypeDORM will make the improvised decision to allow updating attribute values.
Keep an eye out for the next release.

But the workaround you have mentioned above seems fine for now.

**Comment by whimzyLive** [comment]
I am keeping this open to tracking the issue caused by not being able to identify updating attributes.

**Comment by romcok** [comment]
Oh, great. Just subscribed to #150. Thanks 👌
