### ISSUE TITLE
Auto generated ID failing with error message 

### ISSUE THREAD

**Issue by danieljarrett74** [typedorm/typedorm#236]
Following the basic examples in the getting started I've struggled to get things working properly. 

I have an example entity like so which uses  @AutoGenerateAttribute I receive the error below.

```
import {Attribute, Entity, AutoGenerateAttribute, INDEX_TYPE} from '@typedorm/common';
import {AUTO_GENERATE_ATTRIBUTE_STRATEGY} from '@typedorm/common';

@Entity({
  name: 'user', // name of the entity that will be added to each item as an attribute
  // primary key
  primaryKey: {
    partitionKey: 'USER#{{id}}',
    sortKey: 'USER#{{id}}',
  },
  indexes: {
    // specify GSI1 key - "GSI1" named global secondary index needs to exist in above table declaration
    GSI1: {
      partitionKey: 'USER#{{id}}',
      sortKey: 'USER#{{id}}#STATUS#{{status}}',
      type: INDEX_TYPE.GSI,
    },
  },
})
export class User {
  @AutoGenerateAttribute({
    strategy: AUTO_GENERATE_ATTRIBUTE_STRATEGY.UUID4,
  })
  id: string;

  @Attribute()
  name: string;



  @Attribute()
  status: string


}
```

```

createConnection({
  table: appTable,
  entities: [User],
});

const user = new User();
user.name = "Loki";
user.status = "active";


// create user record
getEntityManager()
  .create(user)
  .then((value) => {
    console.log(value);
  })
  .catch((err) => {
    console.log(err);
  });
  ```

`Error: "id" was referenced in USER#{{id}} but it's value could not be resolved.`

If I get rid of the AutoGenerateAttribute and replace it with a simple:

```
  @Attribute()
  id: string;
```
and then explicity set my user Id
```
const user = new User();
user.id = "the-id-i-dont-want-to-have-to-set"
user.name = "Loki";
user.status = "active";
```

Then this works fine.   So there's something a miss whereby it seems that regardless when i call "create" it needs to have that ID value set in the user object. 

I got the same error why I tried to set a default value on the attribute.

```
  @Attribute({
    default: uuid()
  })
  id: string
```

And on a seperate note (i don't know if its related), i get a TypeError when i try to use the following:

```

  @Attribute({
    unique: true
  })
  email: string;

```

I've created a demonstration repo here:
https://github.com/danieljarrett74/dynamodb-orm-tests

**Comment by whimzyLive** [comment]
Closing this as it is no longer active.

**Comment by structurr** [comment]
Hi I'm dealing with this issue right now. I currently have `"target": "es6"` in my tsconfig.

The specific logic I'm getting the error on is:
```
await connection.create<Workspace>(
    new Workspace({
      name,
      description,
    })
  )
```

where `Workspace` is defined as:
```
const ENTITY_TYPE = 'workspace';

@Entity({
  name: ENTITY_TYPE,
  primaryKey: {
    partitionKey: 'workspace/{{workspaceId}}',
    sortKey: 'workspace/{{workspaceId}}',
  },
})
export default class Workspace {
  @AutoGenerateAttribute({
    strategy: AUTO_GENERATE_ATTRIBUTE_STRATEGY.KSUID,
  })
  workspaceId!: string;

  @Attribute()
  name: string;

  @Attribute()
  description: string;

  constructor({ name, description }: { name: string; description: string }) {
    this.name = name;
    this.description = description;
  }
}
```

The above code results in me getting `Error: "workspaceId" was referenced in workspace/{{workspaceId}} but it's value could not be resolved` but this happens _only_ during a test being run with Jest. I don't encounter this issue when running my server normally with node.

Any help would be appreciate as I've been struggling with this for a couple days!

**Comment by danieljarrett74** [comment]
I never found a perfect solution to my packaging problems with typedorm
using typescript.

What would be really handy is a really simple demo app example using TS for
webpack , and esbuild.

The webpack example in the typedorm GitHub is overcomplicated by the fact
that it imports the google template tsconfig. And i couldn't get it to
work.

Solid bare bones examples would i think save a lot of time for many just
starting to use typedorm and prevent them from abandoning it like i almost
did.  Typescript is becoming a standard for nodejs these days and no doubt
the majority of developers using it will want to package their code to add
to a lambda.

An example using layers would be really useful too.

**Comment by danieljarrett74** [comment]
If the moderator puts together a couple of basic examples as mentioned
above, I'd be happy to expand on those to create a lambda layers example
using terraform.
