### ISSUE TITLE
how solved failed batch update

### ISSUE THREAD

**Issue by kzrSauzee** [typedorm/typedorm#247]
const typeDormConnection = NotificationEntity.createConnection(this.NAME, [NotificationEntity], notificationTable);
        const notificationsDDB = await typeDormConnection.entityManager.find(NotificationEntity, {userId: userId.toString()});
![failedbatch](https://user-images.githubusercontent.com/50588767/169079543-63c0b4b0-a665-40f9-bc0e-deeffc892db5.png)
![screenex1](https://user-images.githubusercontent.com/50588767/169079549-5284936d-091d-4780-b1e6-8bf77a2c64dd.png)

        const batchManager = typeDormConnection.batchManager;
        const batchToWrite = new WriteBatch();

        if (notificationsDDB !== undefined) {
            notificationsDDB.items.forEach(item => {
                item.hasBeenRead = 1;

                batchToWrite.addCreateItem(item);
            });

            const batchResponse = await batchManager.write(batchToWrite);

Do someone know why it fails or how can i know the error because i have nothing...

**Comment by whimzyLive** [comment]
Closing this as it is no longer active.
