### ISSUE TITLE
Millisecond precision for AUTO_GENERATE_ATTRIBUTE_STRATEGY.EPOCH_DATE

### ISSUE THREAD

**Issue by tylerthardy** [typedorm/typedorm#248]
Is there a reason why the autogenerated epoch date is converted from milliseconds to seconds?
(I've also seen this pattern in a contractor's dynamodb storage implementation, so I am curious.)
https://github.com/typedorm/typedorm/blob/631b8fa2a5410c068f90b7c66d8449ab139d94a2/packages/core/src/classes/metadata/auto-generated-attribute-metadata.ts#L47

I am willing to open a PR to add support for millisecond epoch date.
Proposing: `AUTO_GENERATE_ATTRIBUTE_STRATEGY.EPOCH_DATE_MILLISECONDS`

**Comment by whimzyLive** [comment]
@tylerthardy 

By definition, Epoch Time is the **number of seconds** that have elapsed since January 1, 1970 (midnight UTC/GMT), thus in seconds.
