### ISSUE TITLE
Error: The security token included in the request is invalid

### ISSUE THREAD

**Issue by sbolanosQB** [typedorm/typedorm#255]
I get this error message when executing a query `The security token included in the request is invalid`, I am guessing I need an extra configuration or something like that

**Comment by whimzyLive** [comment]
I'm not sure if this is related to TypeDORM, Are you able to share more details?

**Comment by whimzyLive** [comment]
Thanks @sbolanosQB  for your feedback, will look into adding an example for this in the docs.
