### ISSUE TITLE
[Bug] Dynamic updating using delete action is not working at all

### ISSUE THREAD

**Issue by jsyoo** [typedorm/typedorm#264]
When try to DELETE an element from a List as described in [using-delete-action](https://github.com/typedorm/typedorm/blob/main/docs/how-to-recipes.md#using-delete-action), I got an error like
```
ValidationException: Invalid UpdateExpression: Incorrect operand type for operator or function; operator: DELETE, operand type: LIST, typeSet: ALLOWED_FOR_DELETE_OPERAND
```
It seems a validation error from aws sdk

do you have any idea to fix this error?

my entity is defined as
```
export class CouponBenefitEntity {
  ...

  @Attribute()
  availableCouponCodes: string[] = [];
  
  ...
}

```
and I tried 
```
    this.entityManager.update(
      CouponBenefitEntity,
      primaryKey,
      {
        availableCouponCodes: {
          DELETE: ['1234'],
        },
      },
      {
        where: {
          id: 'ATTRIBUTE_EXISTS',
        },
      },
    );
```

in [aws dynamodb document](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html), it says `The DELETE action supports only Set data types.` which might not be supported by TypeDorm. TypeDorm seems to support only for List now Set type.

if you have any solutions, please let me know

**Comment by jsyoo** [comment]
@whimzyLive do you have any idea?

**Comment by whimzyLive** [comment]
Hi @jsyoo , Sorry for the later reply - totally missed it.

If I got this right, then you are trying to remove the element from attribute "availableCouponCodes" and not the attribute "availableCouponCodes" itself.

You only use [`DELETE` operation](https://github.com/typedorm/typedorm/blob/main/docs/how-to-recipes.md#using-remove-action) for removing the attribute itself
To remove the elements from an attribute, you need to use [`REMOVE` operation](https://github.com/typedorm/typedorm/blob/main/docs/how-to-recipes.md#using-remove-action).

**Comment by whimzyLive** [comment]
closing this as it has been inactive for over a week. Feel free to reopen if the issue continues happening.
