### ISSUE TITLE
References to V2 AWS SDK and an unknown  DynamoDBClientV3

### ISSUE THREAD

**Issue by NoComment73** [typedorm/typedorm#265]
Have been trying to get 1.15.0-beta.10 running with AWS SDK V3, but I always get the following errors:

`node_modules/@typedorm/document-client/cjs/src/types/document-client-types.d.ts:1:8 - error TS1192: Module '"/Users/xxx/git/yyyy/node_modules/aws-sdk/index"' has no default export.

1 import AWS, { DynamoDB } from 'aws-sdk';
         ~~~

node_modules/@typedorm/document-client/cjs/src/types/document-client-types.d.ts:2:8 - error TS1192: Module '"/Users/xxx/git/yyyy/node_modules/@aws-sdk/client-dynamodb/dist-types/ts3.4/index"' has no default export.

2 import DynamoDBClientV3 from '@aws-sdk/client-dynamodb';
`

DynamoDBClientV3 is something I cannot find in any related code or via Google. And the import of the aws-sdk package looks also weird as this V2 package is not documented to be needed when working with typedorm and AWS SDK V3.

Any idea what goes wrong here? Is this something that can be reproduced, or is it related to my setup (e.g. tsconfig.json misses something important)?

**Comment by whimzyLive** [comment]
@NoComment73 
This looks like an issue with your tsconfig - 
can you see if you have `"allowSyntheticDefaultImports": true,` enabled in `compilerOptions` of the project tsconfig.

The changes to newer SDK v2 and v3 are briefly documented [here ](https://github.com/typedorm/typedorm/tree/beta#initialize-default-connection) or more in detail [here](https://github.com/typedorm/typedorm/blob/beta/docs/upgrading-to-use-the-aws-sdk-v3.md).

You can also refer to the official examples of using TypeDORM with SDK versions 2 and 3 [here](https://github.com/typedorm/typedorm-examples/tree/main/examples).

_P.S. If the typing mentioned above is still an issue with you, please try to reproduce the issue in public repository with minimum config and share the link._

**Comment by NoComment73** [comment]
Setting "allowSyntheticDefaultImports" to true solved the problem, thx!

Don't know if this is related, but I dare to ask here: when I deploy my code as an AWS Lambda, I get the following error:

{
  "errorType": "MissingReflectMetadata",
  "errorMessage": "Could not reflect metadata of type design:type, did you forget to enable \"emitDecoratorMetadata\" on compiler options?",
  "trace": [
    "MissingReflectMetadata: Could not reflect metadata of type design:type, did you forget to enable \"emitDecoratorMetadata\" on compiler options?",
    "    at /var/task/index.js:35433:13",
    "    at __decorateClass (/var/task/index.js:24:24)",
    "    at Object.<anonymous> (/var/task/index.js:35695:1)",
    "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
    "    at Module.load (internal/modules/cjs/loader.js:950:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
    "    at Module.require (internal/modules/cjs/loader.js:974:19)",
    "    at require (internal/modules/cjs/helpers.js:101:18)",
    "    at _tryRequireFile (/var/runtime/UserFunction.js:71:32)"
  ]
}

I've added "import 'reflect-metadata'" into the entry point of the Lambda, have set "emitDecoratorMetadata": true in tsconfig. Any ideas?

**Comment by whimzyLive** [comment]
Hi @NoComment73 

Which build tool are you using? Is that `esbuild` by any chance?

**Comment by NoComment73** [comment]
Yep, esbuild, in the meanwhile, I'm aware of the `experimentalDecorator` issues with it ;-) Thx for the update.
