### ISSUE TITLE
TypeError: class_transformer_1.classToPlain is not a function - using 1.15.0-beta.10

### ISSUE THREAD

**Issue by danieljarrett74** [typedorm/typedorm#267]
I'm not sure if this is an issue with 1.15.0-beta.10. I've upgraded my ORM app and added/modified the following in my package.json file:
```
"dependencies": {
    "@aws-sdk/client-dynamodb": "^3.131.0",
    "@aws-sdk/lib-dynamodb": "^3.131.0",
    "@typedorm/common": "1.15.0-beta.10",
    "@typedorm/core": "1.15.0-beta.10",
    "aws-crt": "^1.13.1",

...
```
I haven't changed any other files (I'm not sure if i needed to?)

Everything builds fine,  but at run time I get the following stack errors.

```
          "stacktrace": [
            "TypeError: class_transformer_1.classToPlain is not a function",
            "    at DocumentClientRequestTransformer.applyClassTransformerFormations (/path-to-my-app/packages/core/src/classes/transformer/base-transformer.ts:52:36)",
            "    at DocumentClientRequestTransformer.toDynamoEntity (/path-to-my-app/packages/core/src/classes/transformer/base-transformer.ts:94:31)",
            "    at DocumentClientRequestTransformer.toDynamoPutItem (/path-to-my-app/packages/core/src/classes/transformer/document-client-request-transformer.ts:136:31)",
            "    at EntityManager.<anonymous> (/path-to-my-app/packages/core/src/classes/manager/entity-manager.ts:198:55)",
            "    at Generator.next (<anonymous>)",
            "    at /path-to-my-app/lib/orm/node_modules/@typedorm/core/cjs/src/classes/manager/entity-manager.js:8:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/path-to-my-app/lib/orm/node_modules/@typedorm/core/cjs/src/classes/manager/entity-manager.js:4:12)",
            "    at EntityManager.create (/path-to-my-app/lib/orm/node_modules/@typedorm/core/cjs/src/classes/manager/entity-manager.js:35:16)",
            "    at /path-to-my-app/myapp/src/resolvers/mutation/createProduct.ts:17:70"
          ]
```

What's kind of odd is the reference to the following file path that doesn't exist:

`/packages/core/src/classes/transformer/base-transformer.ts`

**Comment by whimzyLive** [comment]
@danieljarrett74  Can you confirm if you are getting the same error on the previous beta release (1.15.0-beta.9) and also on the current stable (1.14.11) versions?

**Comment by danieljarrett74** [comment]
@whimzyLive 

I started trying out the other versions you mentioned and noticed that I had a warning in my rollup build that I hadn't noticed before:
```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@typedorm/common (imported by src/dynamodb/entities/activityLog.ts, .....
```

So I updated my rollup config to have the following:

```

import typescript from "@rollup/plugin-typescript";
import json from '@rollup/plugin-json';
import commonjs from '@rollup/plugin-commonjs';
import { nodeResolve } from "@rollup/plugin-node-resolve";

export default {
	"input": "src/index.ts",
	"output": {
		"file": "dist/index.js",
		"format": "esm"
	},
	"external": [],
	"plugins": [
		typescript(),
		nodeResolve({ preferBuiltins: false }),
		commonjs({
			include: 'node_modules/**'
		  }),
		json(),
	]
};

```

And I get the following error.  It looks like there's a problem with the class-transformer module?
```
[!] Error: 'classToPlain' is not exported by node_modules/@typedorm/core/node_modules/class-transformer/esm5/index.js, imported by node_modules/@typedorm/core/esm/src/classes/transformer/base-transformer.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
node_modules/@typedorm/core/esm/src/classes/transformer/base-transformer.js (9:9)
 7: import { isDynamoEntityKeySchema } from '../../helpers/is-dynamo-entity-key-schema';
 8: import { isKeyOfTypeAliasSchema } from '../../helpers/is-key-of-type-alias-schema';
 9: import { classToPlain } from 'class-transformer';

```

**Comment by whimzyLive** [comment]
@danieljarrett74 

Thanks for checking that for me. 
> [ERROR] 14:11:05 Error: Could not dynamically require "@typedorm/common/public-api". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.

This issue will be happening for the stable channel because we were previously using publishing in `umd` format which we are changing to `cjs` and `esm` modules with 1.15.x..

However, the issue you are seeing with `1.15.0-beta.x` should not happen. Are you able to create a public git repo containing just the rollup and typedorm with all your current config (tsconfig) etc and give me a link to that, I will have look at it to see what's failing.

**Comment by danieljarrett74** [comment]
No problem.  You can find it here.

https://github.com/danieljarrett74/typedorm-test

**Comment by whimzyLive** [comment]
@danieljarrett74 

I have made some changes to the given rollup config to make it build successfully - removing the ts -> js from rollup.
Check out all the changes here https://github.com/danieljarrett74/typedorm-test/pull/1.

Also I noticed you are trying to bundle in the aws-sdk with the code itself using rollup, which in my opinion might not be the best decision as there are lots of issues with bundling aws-sdk with rollup - as noted [here](https://github.com/aws/aws-sdk-js/issues/1769).

**Comment by whimzyLive** [comment]
If you are really looking to bundle the code in a way you can deploy it to lambda or something chektout the bundling with webpack. We also have some working examples on how to use it with webpack [here](https://github.com/typedorm/typedorm-examples/tree/main/examples/aws-sdk-v2-typescript-webpack).

**Comment by whimzyLive** [comment]
Closing this as resolved, as there is not really anything I can that needs to be changed with TypeDORM itself. it's mostly the config,

**Comment by danieljarrett74** [comment]
Thanks @whimzyLive thats a great help. 
I currently use webpack to build the project which uses the module/package the the typedorm code is in.  But I thought it might be easier to build this local module with rollup.  And if it wasn't for the following it would be ok :)

---
I tried following your example on your forked repo and it built fine but when I included the built module in my project I got the error:
`ES modules is not supported`

So then I tried to build it as a cjs with the following config (below) and everything worked fine, but at runtime the `AUTO_GENERATE_ATTRIBUTE_STRATEGY.ISO_DATE` isn't working.  As in when I do an insert the created and updated date for the following code don't get created:
```
  @AutoGenerateAttribute({
    strategy: AUTO_GENERATE_ATTRIBUTE_STRATEGY.ISO_DATE,
  })
  createdAt!: string;

  @AutoGenerateAttribute({
    strategy: AUTO_GENERATE_ATTRIBUTE_STRATEGY.ISO_DATE,
    autoUpdate: true,
  })
```


rollup.config.js
```
import typescript from 'rollup-plugin-typescript2'
import json from '@rollup/plugin-json';
import commonjs from '@rollup/plugin-commonjs';
import { nodeResolve } from "@rollup/plugin-node-resolve";
import nodePolyfills from 'rollup-plugin-node-polyfills';

export default {
	"input": "src/index.ts",
	"output": {
		"sourcemap": "true",
		"file": "dist/index.js",
		"format": "cjs"
	},
	"external": ["aws-sdk","uuid"],
	"plugins": [
		commonjs(
			{
				include: 'node_modules/**',
      ignoreGlobal: true
			}
		),
		typescript({ sourceMap: false }),
		nodeResolve({
			preferBuiltins: true		}),
		json(),
	],
	onwarn: function (warning) {
		// Skip certain warnings

		// should intercept ... but doesn't in some rollup versions
		if (warning.code === 'THIS_IS_UNDEFINED') { return; }

		if (warning.code === 'CIRCULAR_DEPENDENCY') { return; }

		// console.warn everything else
		console.warn(warning.message);
	}
};
```

tsconfig.json
```
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "ESNext",
    "strict": true,
    "esModuleInterop": true, 
    "forceConsistentCasingInFileNames": true,
    "moduleResolution": "node",
    "sourceMap": true,
    "declaration": true,
    "declarationDir": "./dist",
    "outDir": "./dist",
    "allowSyntheticDefaultImports":true,
    "skipLibCheck": true,
    "experimentalDecorators": true /* Enables experimental support for ES7 decorators. */,
    "emitDecoratorMetadata": true /* Enables experimental support for emitting type metadata for decorators. */
  },

  "include": ["src/**/*.ts", "dist/**/*.ts"]}
```

package.json
```
{
  "name": "orm",
  "version": "0.1.6",
  "main": "./dist/",
  "files": [
    "dist"
  ],
  "scripts": {
    "build": "rollup -c && npm pack"
  },
  "license": "MIT",
  "dependencies": {
    "@aws-sdk/client-dynamodb": "^3.131.0",
    "@aws-sdk/lib-dynamodb": "^3.131.0",
    "@typedorm/common": "1.15.0-beta.10",
    "@typedorm/core": "1.15.0-beta.10",
    "@types/node": "^18.0.3",
    "aws-crt": "^1.13.1",
    "aws-sdk": "^2.1178.0",
    "reflect-metadata": "^0.1.13",
    "rollup-plugin-node-polyfills": "^0.2.1",
    "ts-node": "^10.8.1",
    "typescript": "^4.7.4"
  },
  "devDependencies": {
    "rollup": "^2.77.0",
    "@rollup/plugin-commonjs": "^22.0.1",
    "@rollup/plugin-json": "^4.1.0",
    "@rollup/plugin-node-resolve": "^13.3.0",
    "rollup-plugin-typescript2": "^0.32.1",
    "@rollup/plugin-typescript": "^8.3.3"
  }
}

```
