### ISSUE TITLE
Errors after updating to beta branch

### ISSUE THREAD

**Issue by sbolanosQB** [typedorm/typedorm#270]
I was using the stable branch until I crash with this issue https://github.com/typedorm/typedorm/issues/220 so I decided to update to the beta branch and I changed my connection to this pattern

```
import {createConnection} from '@typedorm/core';
import {DocumentClientV2} from '@typedorm/document-client';
import AWS from 'aws-sdk';

const documentClient = new DocumentClientV2(new AWS.DynamoDB.DocumentClient());

// initialize with specifying list of entities
createConnection({
  table: myGlobalTable,
  entities: [Organisation],
  documentClient, // <-- When documentClient is not provided, TypeDORM defaults to use the DocumentClientV2
});
```

after the update and the change all my tests start to fail, I am getting errors like `One of the required keys was not given a value` or `class_transformer_1.classToPlain is not a function` so I am wondering if there's something that I am missing after the update. Maybe another configuration update, or an API change?

**Comment by whimzyLive** [comment]
Looks like one of the required packages `class-transformer` is having duplicated versions installed. 
Can you run `npm ls class-transfomer` and let me know what you are seeing?
