### ISSUE TITLE
Beta version using broken package

### ISSUE THREAD

**Issue by sbolanosQB** [typedorm/typedorm#271]
The Beta version is using this package `"class-transformer": "^0.4.0"` which can cause this issue https://github.com/nestjs/nest/issues/8637 The recommended solution is to restrict to version `0.4.0`

**Comment by whimzyLive** [comment]
Thanks, @sbolanosQB  for looking this up. 
I see what's happened. We had seen this issue earlier with the stable branch and it was [hot fixed](https://github.com/typedorm/typedorm/commit/ec6259b96e81f9976a61fb8b7da727d9ebbaa43b) there.

But seems like the change never got merged back into the beta channel.
Will look into it today.

**Comment by sbolanosQB** [comment]
I am using `1.15.0-beta.10` getting this error
```
 TypeError: class_transformer_1.classToPlain is not a function
      at DocumentClientRequestTransformer.applyClassTransformerFormations (../../packages/core/src/classes/transformer/base-transformer.ts:52:36)
 ```
and I found this package https://github.com/typedorm/typedorm/blob/beta/packages/core/package.json#L31

**Comment by whimzyLive** [comment]
Good find. That should definitely be locked as per the previous comment. I'll push out a patch in a bit.

**Comment by whimzyLive** [comment]
Resolved by https://github.com/typedorm/typedorm/commit/6d926e4eef0acc163aa4c004b4877c94f715c9ae

**Comment by sbolanosQB** [comment]
thank you!! 🚀
