### ISSUE TITLE
Query multiple items of the same entity 

### ISSUE THREAD

**Issue by sbolanosQB** [typedorm/typedorm#272]
I wonder what is the best practice to query multiple items of the same entity type. I want to archive something like this 
```
// mongoose example
const batchAuthors = async (ids) => {
  try {
    const authors = await Author.find({ _id: { $in: ids } });
    return authors;
  } catch (err) {
    throw new Error('There was an error getting the Authors');
  }
};
```
Is the `BatchManager` the best way to do it or using `EntityManager` `find` can I archive the same result?

**Comment by whimzyLive** [comment]
hi @sbolanosQB , Yes fetching multiple items by their partition key is really what you want then batch manager is the only option.

**Comment by sbolanosQB** [comment]
thanks!
