### ISSUE TITLE
Override auto generated attributes

### ISSUE THREAD

**Issue by aecorredor** [typedorm/typedorm#316]
It seems like right now we can't override auto-generated attributes (like an ID). It'd be nice for testing purposes, where you want to supply your own ID beforehand, if you're passing it around in a constant before actually committing the object to the DB.

I also was expecting the ID to be autogenerated as soon as the instance is created (e.g. `new User()`). But, it seems like it's only generated once the object is persisted to the database through the entity manager.

**Comment by whimzyLive** [comment]
Yes, it is correct - the ids are not generated until the very end when the request is about to be committed to DynamoDB. This is deliberately done this way to prevent any accidental overrides on auto-generated attributes.

If it is only for testing, can you try mocking the attribute with a static value? If it can't be overridden, please reopen the PR with an example of the test you are trying to write and I'll see if there is something that I can help with.
