### ISSUE TITLE
Can I query a table with Partition Key only when a composite Primary Key is defined?

### ISSUE THREAD

**Issue by zenghou** [typedorm/typedorm#324]
I have a table that  has a composite primary key: `id` (PK) and `reference_id` (SK). 

Is it possible to query records based on `id` alone? I've tried 2 approaches:

1. Excluding sortKey from `Table`
In the table definition, I did not include the `sortKey` and also left it out in the `Entity` definition and ended up getting this error:
```
The provided key element does not match the schema
```

2. Only include `partitionKey` in query
When I exclude `sortKey` in the query params, I get this error

```
One or more parameter values are not valid. The AttributeValue for a key attribute cannot contain an empty string value
```

It seems like if a composite index is defined, I will always require pk + sk for all the operations. Is there any other way to circumvent this?

**Comment by whimzyLive** [comment]
Hi @zenghou,

It should be allowed, as there is nothing wrong with querying composite key items with only PK.

Can you please provide an example of the situation, so that I can better help?
