### ISSUE TITLE
Add support for specifying GSI without a sort key

### ISSUE THREAD

**Issue by whimzyLive** [typedorm/typedorm#335]
### Discussed in https://github.com/typedorm/typedorm/discussions/297

<div type='discussions-op-text'>

<sup>Originally posted by **mathieubrd** December 20, 2022</sup>
Why it is not possible to have a GSI without any sort key?
For example, my use case is to retrieve all items of the same entity (e.g. retrieve all users).
So I would create my entity like so:

```(typescript)
@Entity({
  name: "User",
  primaryKey: {
    partitionKey: "USER#{{email}}",
    sortKey: "USER#{{email}}",
  },
  indexes: {
    entity: {
      type: INDEX_TYPE.GSI,
      partitionKey: "User",
      // No need to have a sort key for this GSI
    },
  },
})
```

To retrieve all my users, I can query on my `entity` GSI with `entity = User`
But `Index` is typed in a way I cannot provide only a partition key.
I try to put an empty string in the sort key but nothing is inserted in my GSI.

Or maybe there is another way to fullfill my use case?</div>

**Comment by mikeki** [comment]
@whimzyLive is there any update here?

**Comment by tgdn** [comment]
I came here to ask the same @whimzyLive

**Comment by asynchroza** [comment]
Any update around this?
