### ISSUE TITLE
class-trasnsformer should be a peer dependency

### ISSUE THREAD

**Issue by nVitius** [typedorm/typedorm#341]
I just ran into an issue where my version of `class-transformer` was different than the one that `typedorm` depends on. 
This was causing the decorators I imported from `class-transformer` to not worked as expected. To avoid the possibility of conflicting versions, this should be in `peerDependencies` instead of `dependencies`.

**Comment by GTRanger** [comment]
I've run into this issue in the past as well. This would be an excellent change.
