### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by NoelBaron** [typedorm/typedorm#382]
Much love for TypeORM. Wondering if this repo is still maintained (saw last commit was 5 months ago).

**Comment by whimzyLive** [comment]
Hey everyone! 

The project's not dead yet—I’ve just been buried in some personal projects. I promise I’ll dive back into all the PRs and issues soon. 🎉 

I could use some help keeping this awesome project running smoothly. 

If you’re passionate about TypeORM and want to pitch in with triaging issues and maintenance, let’s team up! 

🚀 Reply to this thread, if you’re interested. Cheers!
