### ISSUE TITLE
circular peer-dependency: core <-> common

### ISSUE THREAD

**Issue by silberistgold** [typedorm/typedorm#66]
Hi there,

great project. Thank you very much.

I noticed that both packages ("core" and "common") list each other as a peerDependency. I am using serverless-bundle (https://github.com/AnomalyInnovations/serverless-bundle) to package my lambda functions and I have to list both "core" and "common" as "externals" to get typedorm to work after packaging (not 100% sure why that is, webpack seems to strip some necessary parts). However the circular dependency causes the bundler to go into an endless loop trying installing core, common, core, common and so on.
I can manually remove the peer dependencies and get it to work, but this is of course not a real solution.
What do you think about this? I can provide more details if needed.

Cheers
Paul

**Comment by whimzyLive** [comment]
Hi @silberistgold,

Glad to hear that you liked it.

I see the issue is caused because of both referencing each other as required peer dep but it is done that way to have package managers like npm better organise relations. Ideally bundlers like webpack should not be bundling peer deps and therefore there shouldn't be any circular dependency.

I found [this](https://www.npmjs.com/package/webpack-node-externals) on the web, looks like something that can help. I will leave the issue open for now, but if you can't get it to work the way it is right now, will it be possible for you to do a repro in a separate project? I will have look at what can be done there.

**Comment by whimzyLive** [comment]
Hey @silberistgold 

So I was able to look into this, it turns out that all bundlers:  webpack, parcel, rollup... tries to. bundle up peer dependencies. I will remove `core` as a peer dep of common (as you first suggested) and also do a release later today.

**Comment by silberistgold** [comment]
Hey @whimzyLive

did not have the time to look into it, but it seems to have cleared up now.

Thank you very much!

**Comment by mishabruml** [comment]
Hey @silberistgold did you manage to get this library working with AWS Lambda/Serverless framework? Would love to see your config if so! 

I am running into this issue on the lambda: 

```
Seems related to #66
I have tried bundling with serverless-bundle and get a different issue:

{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@typedorm/common/src/decorators/attribute.decorator'",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@typedorm/common/src/decorators/attribute.decorator'",
        "    at _loadUserApp (/var/runtime/UserFunction.js:202:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:242:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

**Comment by silberistgold** [comment]
Hi @mishabruml my working config for `serverless-bundle` looks like this:

```
  bundle:
    tsConfig: "../../tsconfig.json"
    externals:
      - "@typedorm/core"
      - "@typedorm/common"
    ```

In your `tsconfig.json`  set the following:
```
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
```

Please note that I am currently using typedorm version `1.10.2` because of some other issues.

**Comment by mishabruml** [comment]
Hey, thanks for getting back to me. I already had the same config as you, the thing that seemed to fix it was changing the target from ES6 to CommonJS (see https://github.com/typedorm/typedorm/issues/201)

Interestingly, I could not get my serverless project to deploy and run using serverless-webpack, only with serverless-bundle so there must be something else I've missed!

Cheers, Misha
