### ISSUE TITLE
Add support for specifying ConditionExpression when performing `update`

### ISSUE THREAD

**Issue by silberistgold** [typedorm/typedorm#89]
Hi there,

I said it before but I will say it again: great library! Thank you very much.

I currently have a case where I need to pass in a `ConditionExpression` into an update call. As far as I can tell this is not yet possible, but should be easy to expose since you are already using `ConditionExpression` internally as documented [here](https://github.com/typedorm/typedorm/blob/main/docs/how-it-works.md).

Any thoughts on this?

**Comment by whimzyLive** [comment]
Yep, that's correct, there is already a condition expression builder which takes care of building clear and concise condition expressions. I will look into getting this exposed to the entity manager.

**Comment by whimzyLive** [comment]
@silberistgold this is now available to use in 1.12.0-beta.1, please refer to [Condition based updates
](https://github.com/typedorm/typedorm/blob/beta/docs/how-to-recipes.md#condition-based-updates) for more info.
